spring:
  datasource:
    url:  jdbc:mysql://172.29.8.1:3306/lenzencheck-api
    username: test
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    locations: "classpath:db/migration,filesystem:/opt/migration"
    enabled: true
    user: test
    password: password
    baseline-version: 0
    baseline-description: "init"